[package]
name = "bevy_spacemouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spacenav-plus = "0.1.0"
bevy = {version = "0.7", default-features = false}

[dev-dependencies]
bevy = "*"